# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20171027_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbconfig',
            old_name='company_id',
            new_name='companyId',
        ),
        migrations.AlterField(
            model_name='scriptexecution',
            name='DBType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.DBType'),
        ),
    ]
