# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_user'),
        ('database', '0004_auto_20171027_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptexecution',
            name='companyId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
    ]
