# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_scriptexecution_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconfig',
            name='DBName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbconfig',
            name='SID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbconfig',
            name='service_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
