# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolcomponents', '0002_auto_20171027_0807'),
        ('database', '0007_auto_20171108_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptexecution',
            name='server_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='toolcomponents.ServerType'),
            preserve_default=False,
        ),
    ]
