# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_scriptexecution_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconfig',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
