# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20171106_0718'),
        ('database', '0009_auto_20171114_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('targetdestination', models.CharField(max_length=200)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
