# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_ftpexecution'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='AssignFTPUser',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('username', models.CharField(max_length=200)),
        #     ],
        # ),
        migrations.CreateModel(
            name='AssignScriptUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ftpexecution',
            options={'verbose_name': 'FTPExecution', 'verbose_name_plural': 'FTPExecution'},
        ),
        migrations.AlterModelOptions(
            name='scriptexecution',
            options={'verbose_name': 'ScriptExecution', 'verbose_name_plural': 'ScriptExecution'},
        ),
        migrations.AlterField(
            model_name='ftpexecution',
            name='companyId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='ftpexecution',
            name='port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ftpexecution',
            name='targetdestination',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scriptexecution',
            name='companyId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='assignscriptuser',
            name='scriptexecution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ScriptExecution'),
        ),
        # migrations.AddField(
        #     model_name='assignftpuser',
        #     name='config_name',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.FTPExecution'),
        # ),
    ]
