# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20180414_0658'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='assignftpuser',
        #     name='config_name',
        #     field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.FTPExecution'),
        #     preserve_default=False,
        # ),
    ]
