# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_assignftpuser_config_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignFTPUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('config_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.FTPExecution')),
            ],
        ),
    ]
