# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_assignftpuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignscriptuser',
            old_name='scriptexecution',
            new_name='scriptexecute',
        ),
    ]
