# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20180414_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignftpuser',
            name='config_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.FTPExecution'),
        ),
        migrations.AlterField(
            model_name='assignftpuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assignscriptuser',
            name='scriptexecute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.ScriptExecution'),
        ),
        migrations.AlterField(
            model_name='assignscriptuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
