# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20180419_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptexecution',
            name='function',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scriptexecution',
            name='types',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
