# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20180719_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScriptExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbconfig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.DBConfig')),
            ],
        ),
        migrations.AlterField(
            model_name='scriptexecution',
            name='function',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scriptexecution',
            name='types',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userscriptexecution',
            name='script_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ScriptExecution'),
        ),
        migrations.AddField(
            model_name='userscriptexecution',
            name='username_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.AssignScriptUser'),
        ),
    ]
