# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20180726_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptexecution',
            name='dbconfig',
        ),
        migrations.RemoveField(
            model_name='scriptexecution',
            name='server_name',
        ),
    ]
