# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20180727_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignscriptuser',
            name='dbconfig_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='database.DBConfig'),
            preserve_default=False,
        ),
    ]
