# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-18 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_assignscriptuser_dbconfig_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignftpuser',
            options={'verbose_name': 'AssignFTPUser', 'verbose_name_plural': 'AssignFTPUser'},
        ),
        migrations.AlterModelOptions(
            name='assignscriptuser',
            options={'verbose_name': 'AssignScriptUser', 'verbose_name_plural': 'AssignScriptUser'},
        ),
        migrations.RemoveField(
            model_name='assignscriptuser',
            name='dbconfig_id',
        ),
    ]
