# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-24 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20180924_1642'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='scriptdbtype',
        #     options={'verbose_name': 'ScriptDbType', 'verbose_name_plural': 'ScriptDbType'},
        # ),
        # migrations.AlterField(
        #     model_name='scriptexecution',
        #     name='script_dbtype',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.DBType'),
        # ),
    ]
