# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='companyuserassociation',
            options={'verbose_name': 'CompanyUserAssociation', 'verbose_name_plural': 'CompanyUserAssociation'},
        ),
    ]
