# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configureconnection',
            name='execution_script',
            field=models.TextField(max_length=1000),
        ),
    ]
