# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_auto_20171104_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configureconnection',
            name='connection_type',
        ),
    ]
