# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_remove_configureconnection_connection_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configureconnection',
            old_name='dbconfig',
            new_name='DBConfig',
        ),
    ]
