# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_auto_20171107_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configureconnection',
            old_name='DBConfig',
            new_name='dbconfig',
        ),
    ]
